version: '3.8'

services:
  backend:
    build: ./server
    ports:version: '3.8'

services:
  app:
    build: ./server
    ports:
      - "5000:5000"
    volumes:
      - ./server:/app
      - ./client/build:/app/client/build  # Monta o build do React no Flask


